### ISSUE TITLE
The app Meteor can't start with your package

### ISSUE THREAD

**Issue by JeromeVi** [DmitryEfimenko/docker-cmd-js#1]
I added `meteor npm install docker-cmd-js` and when I add `dockerCmdJs = require('docker-cmd-js');` the app crash and I got :
```
W20170518-14:08:32.648(2)? (STDERR) /Users/ng/Desktop/mgmt-docker/.meteor/local/build/programs/server/packages/modules.js:2420
W20170518-14:08:32.709(2)? (STDERR)     static success(...message) {
W20170518-14:08:32.709(2)? (STDERR)                    ^^^
W20170518-14:08:32.709(2)? (STDERR)
W20170518-14:08:32.709(2)? (STDERR) SyntaxError: Unexpected token ...
W20170518-14:08:32.710(2)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170518-14:08:32.710(2)? (STDERR)     at /Users/ng/Desktop/mgmt-docker/.meteor/local/build/programs/server/boot.js:287:30
W20170518-14:08:32.710(2)? (STDERR)     at Array.forEach (native)
W20170518-14:08:32.711(2)? (STDERR)     at Function._.each._.forEach (/Users/ng/.meteor/packages/meteor-tool/.1.4.1_1.fxh4sm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170518-14:08:32.711(2)? (STDERR)     at /Users/ng/Desktop/mgmt-docker/.meteor/local/build/programs/server/boot.js:128:5
```
without it it works and the error comes from this file  https://github.com/DmitryEfimenko/docker-cmd-js/blob/92a4e5ed1f6dcb0eef1251c9a1c67a0e623625c0/dist/src/base.js 
Do you know why ?

http://stackoverflow.com/questions/44047716/how-to-add-docker-cmd-js-into-the-code

**Comment by DmitryEfimenko** [comment]
It looks like it complains about ES6 syntax `static success(...message)`
try this: `meteor add ecmascript`

**Comment by JeromeVi** [comment]
@DmitryEfimenko  it changes nothing. I added it and I still have the same error

**Comment by DmitryEfimenko** [comment]
I changed target to es5. Get latest: 4.0.1, and see if that resolves the issue for you

**Comment by JeromeVi** [comment]
I can start the app with the `require` now :) I'm going to try the commands. 

Thank you very much !

**Comment by JeromeVi** [comment]
@DmitryEfimenko I have a question, why your package the goal is:
send a command to the docker host from a docker container ?


that's right ?

**Comment by DmitryEfimenko** [comment]
not sure I understand what you are asking.
If you are asking what's the purpose of the package, it is to be able to execute docker commands via NodeJs.
